Beginner guide touch up
official-antistasi-community/A3-Antistasi-Docs pull request #77
Opened 2024-10-07 19:16 UTC by ante185

Organised the vanilla factions, added the new vanilla factions
Added missing RHS, 3CB, CUP factions to the list
Added pulau under single maps
Added Mortain to map list and code
Added IFA factions, modsets

2024-10-08 13:24 UTC, targetingsnake requested changes
looks good, please check for the correct alphabetic order as the lists where ordered by it

2024-10-08 13:24 UTC, targetingsnake commented on source/beginners_guide/raw_beginners_guide.rst
> +      - `UMB Columbia <https://steamcommunity.com/sharedfiles/filedetails/?id=2266710560>`_
this was alphabeticly sorted, `UMB Columbia` starts with a 'u' so it should be further down the line

2024-10-08 13:24 UTC, targetingsnake commented on source/beginners_guide/raw_beginners_guide.rst
> +         *  - Mortain
please put this before Normandy, then we would have a good alphabetic order

2024-10-08 13:24 UTC, targetingsnake commented on source/beginners_guide/raw_beginners_guide.rst
> +      - Mortain
switch Normandy and mortain for alphabetic order pls

2024-10-13 13:52 UTC, targetingsnake commented
@ante185 please recheck i did the ordering real quick would merge tomorrow afternoon/evening

2024-10-14 17:28 UTC, targetingsnake approved these changes

2024-10-14 17:28 UTC, merged

2024-10-14 23:23 UTC, Giddius commented
**__Just as fyi:__**

If there is a problem with building it or something else I can help, then don't hesitate to reach out to me *(dm, ping, carrier pigeon)*!